In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# Preprocessing of Data

# Loading of dataset (PSEI)
# We will only use the closing prices, hence we set usecols to index:4
data = np.genfromtxt('data/PSEI.csv', delimiter=',', skip_header=1, usecols=4)

# Splitting of dataset for training (80%) and testing (20%)
# Split data into training and testing
len_train = int(len(data) * 0.80)
data_train = data[:len_train]
data_test = data[len_train:]

# Creating a windowed datasets for training, using the following window sizes (5, 10, 15, 20)
windowed_sizes = [5, 10, 15, 20]
windowed_data_train = [0, 0, 0, 0]

idx_counter = 0
for window_size in windowed_sizes:
    train_data = np.zeros((len(data_train) - window_size, window_size))
    for i in range(len(data_train) - window_size):
        train_data[i] = data_train[i:i + window_size]
    windowed_data_train[idx_counter] = train_data
    idx_counter += 1

y_data_train = [[], [], [], []]
# For y_data_train, in window_size = 5
for i in range(len(windowed_data_train[0])):
    y_data_train[0].append(windowed_data_train[0][i][1])
# For y_data_train, in window_size = 10
for i in range(len(windowed_data_train[1])):
    y_data_train[1].append(windowed_data_train[1][i][1])
# For y_data_train, in window_size = 15
for i in range(len(windowed_data_train[2])):
    y_data_train[2].append(windowed_data_train[2][i][1])
# For y_data_train, in window_size = 20
for i in range(len(windowed_data_train[3])):
    y_data_train[3].append(windowed_data_train[3][i][1])


# Creating a windowed datasets for testing, using the following window sizes (5, 10, 15, 20)
windowed_sizes = [5, 10, 15, 20]
windowed_data_test = [0, 0, 0, 0]

idx_counter = 0
for window_size in windowed_sizes:
    test_data = np.zeros((len(data_test) - window_size, window_size))
    for i in range(len(data_test) - window_size):
        test_data[i] = data_test[i:i + window_size]
    windowed_data_test[idx_counter] = test_data
    idx_counter += 1

y_data_test = [[], [], [], []]
# For y_data_test, in window_size = 5
for i in range(len(windowed_data_test[0])):
    y_data_test[0].append(windowed_data_test[0][i][1])
# For y_data_test, in window_size = 10
for i in range(len(windowed_data_test[1])):
    y_data_test[1].append(windowed_data_test[1][i][1])
# For y_data_test, in window_size = 15
for i in range(len(windowed_data_test[2])):
    y_data_test[2].append(windowed_data_test[2][i][1])
# For y_data_test, in window_size = 20
for i in range(len(windowed_data_test[3])):
    y_data_test[3].append(windowed_data_test[3][i][1])

In [3]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=10)

In [4]:
# Baseline Model for window_size = 5
window_size = windowed_sizes[0]

model_baseline5 =  tf.keras.Sequential()
model_baseline5.add(tf.keras.layers.Dense(1, input_shape=(window_size,)))
model_baseline5.layers[0].trainable = True

# Compile the model_baseline5
model_baseline5.compile(optimizer='adam',
                 loss='mse',
                 metrics=['mae', 
                          'mape', 
                          'mean_squared_error'])

# Train the model_baseline5
y_data_train0 = np.array(y_data_train[0])
y_data_test0 = np.array(y_data_test[0])
model_baseline5.fit(windowed_data_train[0], 
             y_data_train0, 
             epochs=1_000,
             verbose=0,
             validation_data=(windowed_data_test[0], y_data_test0),
             callbacks=[callback])

In [5]:
# Baseline Model for window_size = 10
window_size = windowed_sizes[1]

model_baseline10 =  tf.keras.Sequential()
model_baseline10.add(tf.keras.layers.Dense(1, input_shape=(window_size,)))
model_baseline10.layers[0].trainable = True

# Compile the model_baseline10
model_baseline10.compile(optimizer='adam',
                    loss='mse',
                    metrics=['mae',
                            'mape',
                            'mean_squared_error'])

# Train the model_baseline10
y_data_train1 = np.array(y_data_train[1])
y_data_test1 = np.array(y_data_test[1])
model_baseline10.fit(windowed_data_train[1],
                y_data_train1,
                epochs=1_000,
                verbose=0,
                validation_data=(windowed_data_test[1], y_data_test1),
                callbacks=[callback])

In [6]:
# Baseline Model for window_size = 15
window_size = windowed_sizes[2]

model_baseline15 =  tf.keras.Sequential()
model_baseline15.add(tf.keras.layers.Dense(1, input_shape=(window_size,)))
model_baseline15.layers[0].trainable = True

# Compile the model_baseline15
model_baseline15.compile(optimizer='adam',
                    loss='mse',
                    metrics=['mae',
                            'mape',
                            'mean_squared_error'])

# Train the model_baseline15
y_data_train2 = np.array(y_data_train[2])
y_data_test2 = np.array(y_data_test[2])
model_baseline15.fit(windowed_data_train[2],
                y_data_train2,
                epochs=1_000,
                verbose=0,
                validation_data=(windowed_data_test[2], y_data_test2),
                callbacks=[callback])

In [7]:
# Baseline Model for window_size = 20
window_size = windowed_sizes[3]

model_baseline20 =  tf.keras.Sequential()
model_baseline20.add(tf.keras.layers.Dense(1, input_shape=(window_size,)))
model_baseline20.layers[0].trainable = True

# Compile the model_baseline20
model_baseline20.compile(optimizer='adam',
                    loss='mse',
                    metrics=['mae',
                            'mape',
                            'mean_squared_error'])

# Train the model_baseline20
y_data_train3 = np.array(y_data_train[3])
y_data_test3 = np.array(y_data_test[3])
model_baseline20.fit(windowed_data_train[3],
                y_data_train3,
                epochs=1_000,
                verbose=0,
                validation_data=(windowed_data_test[3], y_data_test3),
                callbacks=[callback])

In [8]:
print("METRIC RESULTS")
print(f"For window_size = 5: {model_baseline5.get_metrics_result()}\n")
print(f"For window_size = 10: {model_baseline10.get_metrics_result()}\n")
print(f"For window_size = 15: {model_baseline15.get_metrics_result()}\n")
print(f"For window_size = 20: {model_baseline20.get_metrics_result()}\n")

METRIC RESULTS
For window_size = 5: {'loss': <tf.Tensor: shape=(), dtype=float32, numpy=11340.848>, 'mae': <tf.Tensor: shape=(), dtype=float32, numpy=78.48051>, 'mape': <tf.Tensor: shape=(), dtype=float32, numpy=1.1527511>, 'mean_squared_error': <tf.Tensor: shape=(), dtype=float32, numpy=11340.848>}

For window_size = 10: {'loss': <tf.Tensor: shape=(), dtype=float32, numpy=676.18286>, 'mae': <tf.Tensor: shape=(), dtype=float32, numpy=19.639399>, 'mape': <tf.Tensor: shape=(), dtype=float32, numpy=0.286307>, 'mean_squared_error': <tf.Tensor: shape=(), dtype=float32, numpy=676.18286>}

For window_size = 15: {'loss': <tf.Tensor: shape=(), dtype=float32, numpy=3537.5012>, 'mae': <tf.Tensor: shape=(), dtype=float32, numpy=44.18517>, 'mape': <tf.Tensor: shape=(), dtype=float32, numpy=0.64862263>, 'mean_squared_error': <tf.Tensor: shape=(), dtype=float32, numpy=3537.5012>}

For window_size = 20: {'loss': <tf.Tensor: shape=(), dtype=float32, numpy=2164.3389>, 'mae': <tf.Tensor: shape=(), dtype=

In [9]:
# Save Models
model_baseline5.save('exported_models/model_baseline5.keras')
model_baseline10.save('exported_models/model_baseline10.keras')
model_baseline15.save('exported_models/model_baseline15.keras')
model_baseline20.save('exported_models/model_baseline20.keras')